/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RfButtonType, RfButtonVariant } from "./components/rf-button/rf-button";
import { MealDay, MealSlot, PlannedMeal, RecipeFilterValue, RecipeFormErrors, RecipeId, RecipeSearchResult, SelectOption, UserRecipeDraft } from "./utils/types";
export { RfButtonType, RfButtonVariant } from "./components/rf-button/rf-button";
export { MealDay, MealSlot, PlannedMeal, RecipeFilterValue, RecipeFormErrors, RecipeId, RecipeSearchResult, SelectOption, UserRecipeDraft } from "./utils/types";
export namespace Components {
    /**
     * Shared accessible button primitive.
     */
    interface RfButton {
        /**
          * Accessible name when content is icon-only
         */
        "ariaLabel"?: string;
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Native button type
          * @default 'button'
         */
        "type": RfButtonType;
        /**
          * Visual style
          * @default 'primary'
         */
        "variant": RfButtonVariant;
    }
    /**
     * Empty placeholder with optional CTA slot.
     */
    interface RfEmptyState {
        /**
          * Heading text
          * @default 'Nothing here yet'
         */
        "heading": string;
        /**
          * Supporting message
          * @default ''
         */
        "message": string;
    }
    /**
     * Accessible favorite (heart) toggle button.
     */
    interface RfFavoriteButton {
        /**
          * Whether the item is favorited
          * @default false
         */
        "active": boolean;
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Accessible label when active
          * @default 'Remove from favorites'
         */
        "labelActive": string;
        /**
          * Accessible label when inactive
          * @default 'Add to favorites'
         */
        "labelInactive": string;
    }
    /**
     * Category / area / ingredient filter panel.
     */
    interface RfFilterPanel {
        /**
          * Area / cuisine options
          * @default []
         */
        "areas": string[] | SelectOption[] | string;
        /**
          * Category options (strings or SelectOption / JSON)
          * @default []
         */
        "categories": string[] | SelectOption[] | string;
        /**
          * Show ingredient text field
          * @default true
         */
        "showIngredient": boolean;
        /**
          * Current filter value
          * @default {}
         */
        "value": RecipeFilterValue | string;
    }
    /**
     * Labeled text input with optional error and hint slot.
     */
    interface RfInput {
        /**
          * Autocomplete hint
         */
        "autocomplete"?: string;
        /**
          * Disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message (sets aria-invalid)
         */
        "error"?: string;
        /**
          * Visible label
          * @default ''
         */
        "label": string;
        /**
          * Name attribute
         */
        "name"?: string;
        /**
          * Placeholder
          * @default ''
         */
        "placeholder": string;
        /**
          * Required
          * @default false
         */
        "required": boolean;
        /**
          * Input type
          * @default 'text'
         */
        "type": string;
        /**
          * Controlled value
          * @default ''
         */
        "value": string;
    }
    /**
     * Accessible loading indicator for content regions.
     */
    interface RfLoadingState {
        /**
          * Accessible / visible label
          * @default 'Loading…'
         */
        "label": string;
    }
    /**
     * Single planned meal cell for the week planner.
     */
    interface RfMealPlanCard {
        /**
          * Day of week
         */
        "day": MealDay;
        /**
          * Planned meal (optional when empty slot)
         */
        "meal"?: PlannedMeal | string;
        /**
          * Meal slot (breakfast / lunch / dinner). Uses attribute `meal-slot` to avoid clashing with the HTML `slot` attribute.
         */
        "mealSlot": MealSlot;
    }
    /**
     * Seven-day meal planner grid.
     */
    interface RfMealPlanWeek {
        /**
          * Planned meals for the week
          * @default []
         */
        "meals": PlannedMeal[] | string;
        /**
          * ISO date for week start (Monday)
          * @default ''
         */
        "weekStart": string;
    }
    /**
     * Accessible modal dialog with focus trap basics and Escape to close.
     */
    interface RfModal {
        /**
          * Close when backdrop is clicked
          * @default true
         */
        "closeOnBackdrop": boolean;
        /**
          * Dialog heading
          * @default ''
         */
        "heading": string;
        /**
          * Whether the dialog is open
          * @default false
         */
        "open": boolean;
    }
    /**
     * Recipe summary card.
     */
    interface RfRecipeCard {
        /**
          * Whether this recipe is favorited
          * @default false
         */
        "favorited": boolean;
        /**
          * Hide the built-in favorite control
          * @default false
         */
        "hideFavorite": boolean;
        /**
          * Recipe summary (object or JSON string)
         */
        "recipe": RecipeSearchResult | string;
    }
    /**
     * Presentational create/edit recipe form. Validation messages come from the host via `errors`.
     */
    interface RfRecipeForm {
        /**
          * Disable submit
          * @default false
         */
        "disabled": boolean;
        /**
          * Field-level errors from the app
          * @default {}
         */
        "errors": RecipeFormErrors | string;
        /**
          * Submit button label
          * @default 'Save recipe'
         */
        "submitLabel": string;
        /**
          * Form draft value
          * @default emptyDraft()
         */
        "value": UserRecipeDraft | string;
    }
    /**
     * Responsive grid of recipe cards. Card events bubble as custom events from this host.
     */
    interface RfRecipeGrid {
        /**
          * Favorited recipe ids
          * @default []
         */
        "favoritedIds": RecipeId[] | string;
        /**
          * Accessible label for the grid
          * @default 'Recipes'
         */
        "label": string;
        /**
          * Recipes to render
          * @default []
         */
        "recipes": RecipeSearchResult[] | string;
    }
    /**
     * Search field with submit control.
     */
    interface RfSearchBar {
        /**
          * Disables the whole control
          * @default false
         */
        "disabled": boolean;
        /**
          * Accessible label for the search field
          * @default 'Search recipes'
         */
        "label": string;
        /**
          * Shows loading / disables submit
          * @default false
         */
        "loading": boolean;
        /**
          * Placeholder text
          * @default 'Search recipes…'
         */
        "placeholder": string;
        /**
          * Submit button label
          * @default 'Search'
         */
        "submitLabel": string;
        /**
          * Current query
          * @default ''
         */
        "value": string;
    }
    /**
     * Labeled select control.
     */
    interface RfSelect {
        /**
          * Disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Visible label
          * @default ''
         */
        "label": string;
        /**
          * Name attribute
         */
        "name"?: string;
        /**
          * Options list (object or JSON string for attribute usage)
          * @default []
         */
        "options": SelectOption[] | string;
        /**
          * Placeholder option label
          * @default 'Select…'
         */
        "placeholder": string;
        /**
          * Required
          * @default false
         */
        "required": boolean;
        /**
          * Selected value
          * @default ''
         */
        "value": string;
    }
}
export interface RfButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfButtonElement;
}
export interface RfFavoriteButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfFavoriteButtonElement;
}
export interface RfFilterPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfFilterPanelElement;
}
export interface RfInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfInputElement;
}
export interface RfMealPlanCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfMealPlanCardElement;
}
export interface RfMealPlanWeekCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfMealPlanWeekElement;
}
export interface RfModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfModalElement;
}
export interface RfRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfRecipeCardElement;
}
export interface RfRecipeFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfRecipeFormElement;
}
export interface RfRecipeGridCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfRecipeGridElement;
}
export interface RfSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfSearchBarElement;
}
export interface RfSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRfSelectElement;
}
declare global {
    interface HTMLRfButtonElementEventMap {
        "rfClick": void;
    }
    /**
     * Shared accessible button primitive.
     */
    interface HTMLRfButtonElement extends Components.RfButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfButtonElementEventMap>(type: K, listener: (this: HTMLRfButtonElement, ev: RfButtonCustomEvent<HTMLRfButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfButtonElementEventMap>(type: K, listener: (this: HTMLRfButtonElement, ev: RfButtonCustomEvent<HTMLRfButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfButtonElement: {
        prototype: HTMLRfButtonElement;
        new (): HTMLRfButtonElement;
    };
    /**
     * Empty placeholder with optional CTA slot.
     */
    interface HTMLRfEmptyStateElement extends Components.RfEmptyState, HTMLStencilElement {
    }
    var HTMLRfEmptyStateElement: {
        prototype: HTMLRfEmptyStateElement;
        new (): HTMLRfEmptyStateElement;
    };
    interface HTMLRfFavoriteButtonElementEventMap {
        "rfToggle": { active: boolean };
    }
    /**
     * Accessible favorite (heart) toggle button.
     */
    interface HTMLRfFavoriteButtonElement extends Components.RfFavoriteButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfFavoriteButtonElementEventMap>(type: K, listener: (this: HTMLRfFavoriteButtonElement, ev: RfFavoriteButtonCustomEvent<HTMLRfFavoriteButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfFavoriteButtonElementEventMap>(type: K, listener: (this: HTMLRfFavoriteButtonElement, ev: RfFavoriteButtonCustomEvent<HTMLRfFavoriteButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfFavoriteButtonElement: {
        prototype: HTMLRfFavoriteButtonElement;
        new (): HTMLRfFavoriteButtonElement;
    };
    interface HTMLRfFilterPanelElementEventMap {
        "rfFilterChange": RecipeFilterValue;
    }
    /**
     * Category / area / ingredient filter panel.
     */
    interface HTMLRfFilterPanelElement extends Components.RfFilterPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfFilterPanelElementEventMap>(type: K, listener: (this: HTMLRfFilterPanelElement, ev: RfFilterPanelCustomEvent<HTMLRfFilterPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfFilterPanelElementEventMap>(type: K, listener: (this: HTMLRfFilterPanelElement, ev: RfFilterPanelCustomEvent<HTMLRfFilterPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfFilterPanelElement: {
        prototype: HTMLRfFilterPanelElement;
        new (): HTMLRfFilterPanelElement;
    };
    interface HTMLRfInputElementEventMap {
        "rfInput": string;
        "rfChange": string;
    }
    /**
     * Labeled text input with optional error and hint slot.
     */
    interface HTMLRfInputElement extends Components.RfInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfInputElementEventMap>(type: K, listener: (this: HTMLRfInputElement, ev: RfInputCustomEvent<HTMLRfInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfInputElementEventMap>(type: K, listener: (this: HTMLRfInputElement, ev: RfInputCustomEvent<HTMLRfInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfInputElement: {
        prototype: HTMLRfInputElement;
        new (): HTMLRfInputElement;
    };
    /**
     * Accessible loading indicator for content regions.
     */
    interface HTMLRfLoadingStateElement extends Components.RfLoadingState, HTMLStencilElement {
    }
    var HTMLRfLoadingStateElement: {
        prototype: HTMLRfLoadingStateElement;
        new (): HTMLRfLoadingStateElement;
    };
    interface HTMLRfMealPlanCardElementEventMap {
        "rfRemove": { meal: PlannedMeal };
        "rfSelect": {
    day: MealDay;
    slot: MealSlot;
    meal?: PlannedMeal;
  };
    }
    /**
     * Single planned meal cell for the week planner.
     */
    interface HTMLRfMealPlanCardElement extends Components.RfMealPlanCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfMealPlanCardElementEventMap>(type: K, listener: (this: HTMLRfMealPlanCardElement, ev: RfMealPlanCardCustomEvent<HTMLRfMealPlanCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfMealPlanCardElementEventMap>(type: K, listener: (this: HTMLRfMealPlanCardElement, ev: RfMealPlanCardCustomEvent<HTMLRfMealPlanCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfMealPlanCardElement: {
        prototype: HTMLRfMealPlanCardElement;
        new (): HTMLRfMealPlanCardElement;
    };
    interface HTMLRfMealPlanWeekElementEventMap {
        "rfSlotClick": {
    day: MealDay;
    slot: MealSlot;
    meal?: PlannedMeal;
  };
        "rfMealRemove": { meal: PlannedMeal };
        "rfMealMove": {
    mealId: string;
    toDay: MealDay;
    toSlot: MealSlot;
  };
    }
    /**
     * Seven-day meal planner grid.
     */
    interface HTMLRfMealPlanWeekElement extends Components.RfMealPlanWeek, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfMealPlanWeekElementEventMap>(type: K, listener: (this: HTMLRfMealPlanWeekElement, ev: RfMealPlanWeekCustomEvent<HTMLRfMealPlanWeekElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfMealPlanWeekElementEventMap>(type: K, listener: (this: HTMLRfMealPlanWeekElement, ev: RfMealPlanWeekCustomEvent<HTMLRfMealPlanWeekElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfMealPlanWeekElement: {
        prototype: HTMLRfMealPlanWeekElement;
        new (): HTMLRfMealPlanWeekElement;
    };
    interface HTMLRfModalElementEventMap {
        "rfClose": void;
    }
    /**
     * Accessible modal dialog with focus trap basics and Escape to close.
     */
    interface HTMLRfModalElement extends Components.RfModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfModalElementEventMap>(type: K, listener: (this: HTMLRfModalElement, ev: RfModalCustomEvent<HTMLRfModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfModalElementEventMap>(type: K, listener: (this: HTMLRfModalElement, ev: RfModalCustomEvent<HTMLRfModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfModalElement: {
        prototype: HTMLRfModalElement;
        new (): HTMLRfModalElement;
    };
    interface HTMLRfRecipeCardElementEventMap {
        "rfRecipeSelect": { recipe: RecipeSearchResult };
        "rfFavoriteToggle": {
    recipe: RecipeSearchResult;
    active: boolean;
  };
    }
    /**
     * Recipe summary card.
     */
    interface HTMLRfRecipeCardElement extends Components.RfRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfRecipeCardElementEventMap>(type: K, listener: (this: HTMLRfRecipeCardElement, ev: RfRecipeCardCustomEvent<HTMLRfRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfRecipeCardElementEventMap>(type: K, listener: (this: HTMLRfRecipeCardElement, ev: RfRecipeCardCustomEvent<HTMLRfRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfRecipeCardElement: {
        prototype: HTMLRfRecipeCardElement;
        new (): HTMLRfRecipeCardElement;
    };
    interface HTMLRfRecipeFormElementEventMap {
        "rfChange": UserRecipeDraft;
        "rfSubmit": UserRecipeDraft;
    }
    /**
     * Presentational create/edit recipe form. Validation messages come from the host via `errors`.
     */
    interface HTMLRfRecipeFormElement extends Components.RfRecipeForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfRecipeFormElementEventMap>(type: K, listener: (this: HTMLRfRecipeFormElement, ev: RfRecipeFormCustomEvent<HTMLRfRecipeFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfRecipeFormElementEventMap>(type: K, listener: (this: HTMLRfRecipeFormElement, ev: RfRecipeFormCustomEvent<HTMLRfRecipeFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfRecipeFormElement: {
        prototype: HTMLRfRecipeFormElement;
        new (): HTMLRfRecipeFormElement;
    };
    interface HTMLRfRecipeGridElementEventMap {
        "rfRecipeSelect": { recipe: RecipeSearchResult };
        "rfFavoriteToggle": {
    recipe: RecipeSearchResult;
    active: boolean;
  };
    }
    /**
     * Responsive grid of recipe cards. Card events bubble as custom events from this host.
     */
    interface HTMLRfRecipeGridElement extends Components.RfRecipeGrid, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfRecipeGridElementEventMap>(type: K, listener: (this: HTMLRfRecipeGridElement, ev: RfRecipeGridCustomEvent<HTMLRfRecipeGridElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfRecipeGridElementEventMap>(type: K, listener: (this: HTMLRfRecipeGridElement, ev: RfRecipeGridCustomEvent<HTMLRfRecipeGridElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfRecipeGridElement: {
        prototype: HTMLRfRecipeGridElement;
        new (): HTMLRfRecipeGridElement;
    };
    interface HTMLRfSearchBarElementEventMap {
        "rfSearch": { query: string };
    }
    /**
     * Search field with submit control.
     */
    interface HTMLRfSearchBarElement extends Components.RfSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfSearchBarElementEventMap>(type: K, listener: (this: HTMLRfSearchBarElement, ev: RfSearchBarCustomEvent<HTMLRfSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfSearchBarElementEventMap>(type: K, listener: (this: HTMLRfSearchBarElement, ev: RfSearchBarCustomEvent<HTMLRfSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfSearchBarElement: {
        prototype: HTMLRfSearchBarElement;
        new (): HTMLRfSearchBarElement;
    };
    interface HTMLRfSelectElementEventMap {
        "rfChange": string;
    }
    /**
     * Labeled select control.
     */
    interface HTMLRfSelectElement extends Components.RfSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRfSelectElementEventMap>(type: K, listener: (this: HTMLRfSelectElement, ev: RfSelectCustomEvent<HTMLRfSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRfSelectElementEventMap>(type: K, listener: (this: HTMLRfSelectElement, ev: RfSelectCustomEvent<HTMLRfSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRfSelectElement: {
        prototype: HTMLRfSelectElement;
        new (): HTMLRfSelectElement;
    };
    interface HTMLElementTagNameMap {
        "rf-button": HTMLRfButtonElement;
        "rf-empty-state": HTMLRfEmptyStateElement;
        "rf-favorite-button": HTMLRfFavoriteButtonElement;
        "rf-filter-panel": HTMLRfFilterPanelElement;
        "rf-input": HTMLRfInputElement;
        "rf-loading-state": HTMLRfLoadingStateElement;
        "rf-meal-plan-card": HTMLRfMealPlanCardElement;
        "rf-meal-plan-week": HTMLRfMealPlanWeekElement;
        "rf-modal": HTMLRfModalElement;
        "rf-recipe-card": HTMLRfRecipeCardElement;
        "rf-recipe-form": HTMLRfRecipeFormElement;
        "rf-recipe-grid": HTMLRfRecipeGridElement;
        "rf-search-bar": HTMLRfSearchBarElement;
        "rf-select": HTMLRfSelectElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * Shared accessible button primitive.
     */
    interface RfButton {
        /**
          * Accessible name when content is icon-only
         */
        "ariaLabel"?: string;
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted on activation (no DOM event in detail — host owns intent)
         */
        "onRfClick"?: (event: RfButtonCustomEvent<void>) => void;
        /**
          * Native button type
          * @default 'button'
         */
        "type"?: RfButtonType;
        /**
          * Visual style
          * @default 'primary'
         */
        "variant"?: RfButtonVariant;
    }
    /**
     * Empty placeholder with optional CTA slot.
     */
    interface RfEmptyState {
        /**
          * Heading text
          * @default 'Nothing here yet'
         */
        "heading"?: string;
        /**
          * Supporting message
          * @default ''
         */
        "message"?: string;
    }
    /**
     * Accessible favorite (heart) toggle button.
     */
    interface RfFavoriteButton {
        /**
          * Whether the item is favorited
          * @default false
         */
        "active"?: boolean;
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Accessible label when active
          * @default 'Remove from favorites'
         */
        "labelActive"?: string;
        /**
          * Accessible label when inactive
          * @default 'Add to favorites'
         */
        "labelInactive"?: string;
        /**
          * Emitted when the user toggles favorite
         */
        "onRfToggle"?: (event: RfFavoriteButtonCustomEvent<{ active: boolean }>) => void;
    }
    /**
     * Category / area / ingredient filter panel.
     */
    interface RfFilterPanel {
        /**
          * Area / cuisine options
          * @default []
         */
        "areas"?: string[] | SelectOption[] | string;
        /**
          * Category options (strings or SelectOption / JSON)
          * @default []
         */
        "categories"?: string[] | SelectOption[] | string;
        /**
          * Emitted when any filter field changes
         */
        "onRfFilterChange"?: (event: RfFilterPanelCustomEvent<RecipeFilterValue>) => void;
        /**
          * Show ingredient text field
          * @default true
         */
        "showIngredient"?: boolean;
        /**
          * Current filter value
          * @default {}
         */
        "value"?: RecipeFilterValue | string;
    }
    /**
     * Labeled text input with optional error and hint slot.
     */
    interface RfInput {
        /**
          * Autocomplete hint
         */
        "autocomplete"?: string;
        /**
          * Disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message (sets aria-invalid)
         */
        "error"?: string;
        /**
          * Visible label
          * @default ''
         */
        "label"?: string;
        /**
          * Name attribute
         */
        "name"?: string;
        /**
          * Emitted on change / blur commit
         */
        "onRfChange"?: (event: RfInputCustomEvent<string>) => void;
        /**
          * Emitted on every input
         */
        "onRfInput"?: (event: RfInputCustomEvent<string>) => void;
        /**
          * Placeholder
          * @default ''
         */
        "placeholder"?: string;
        /**
          * Required
          * @default false
         */
        "required"?: boolean;
        /**
          * Input type
          * @default 'text'
         */
        "type"?: string;
        /**
          * Controlled value
          * @default ''
         */
        "value"?: string;
    }
    /**
     * Accessible loading indicator for content regions.
     */
    interface RfLoadingState {
        /**
          * Accessible / visible label
          * @default 'Loading…'
         */
        "label"?: string;
    }
    /**
     * Single planned meal cell for the week planner.
     */
    interface RfMealPlanCard {
        /**
          * Day of week
         */
        "day": MealDay;
        /**
          * Planned meal (optional when empty slot)
         */
        "meal"?: PlannedMeal | string;
        /**
          * Meal slot (breakfast / lunch / dinner). Uses attribute `meal-slot` to avoid clashing with the HTML `slot` attribute.
         */
        "mealSlot": MealSlot;
        /**
          * Emitted when remove is clicked
         */
        "onRfRemove"?: (event: RfMealPlanCardCustomEvent<{ meal: PlannedMeal }>) => void;
        /**
          * Emitted when the meal / empty slot is selected
         */
        "onRfSelect"?: (event: RfMealPlanCardCustomEvent<{
    day: MealDay;
    slot: MealSlot;
    meal?: PlannedMeal;
  }>) => void;
    }
    /**
     * Seven-day meal planner grid.
     */
    interface RfMealPlanWeek {
        /**
          * Planned meals for the week
          * @default []
         */
        "meals"?: PlannedMeal[] | string;
        /**
          * Emitted when a meal should move (drag/drop or host-driven); detail includes source + target
         */
        "onRfMealMove"?: (event: RfMealPlanWeekCustomEvent<{
    mealId: string;
    toDay: MealDay;
    toSlot: MealSlot;
  }>) => void;
        /**
          * Emitted when a meal is removed
         */
        "onRfMealRemove"?: (event: RfMealPlanWeekCustomEvent<{ meal: PlannedMeal }>) => void;
        /**
          * Emitted when an empty or filled slot is clicked
         */
        "onRfSlotClick"?: (event: RfMealPlanWeekCustomEvent<{
    day: MealDay;
    slot: MealSlot;
    meal?: PlannedMeal;
  }>) => void;
        /**
          * ISO date for week start (Monday)
          * @default ''
         */
        "weekStart"?: string;
    }
    /**
     * Accessible modal dialog with focus trap basics and Escape to close.
     */
    interface RfModal {
        /**
          * Close when backdrop is clicked
          * @default true
         */
        "closeOnBackdrop"?: boolean;
        /**
          * Dialog heading
          * @default ''
         */
        "heading"?: string;
        /**
          * Emitted when the dialog requests close
         */
        "onRfClose"?: (event: RfModalCustomEvent<void>) => void;
        /**
          * Whether the dialog is open
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * Recipe summary card.
     */
    interface RfRecipeCard {
        /**
          * Whether this recipe is favorited
          * @default false
         */
        "favorited"?: boolean;
        /**
          * Hide the built-in favorite control
          * @default false
         */
        "hideFavorite"?: boolean;
        /**
          * Emitted when favorite is toggled from the card
         */
        "onRfFavoriteToggle"?: (event: RfRecipeCardCustomEvent<{
    recipe: RecipeSearchResult;
    active: boolean;
  }>) => void;
        /**
          * Emitted when the card body is activated
         */
        "onRfRecipeSelect"?: (event: RfRecipeCardCustomEvent<{ recipe: RecipeSearchResult }>) => void;
        /**
          * Recipe summary (object or JSON string)
         */
        "recipe": RecipeSearchResult | string;
    }
    /**
     * Presentational create/edit recipe form. Validation messages come from the host via `errors`.
     */
    interface RfRecipeForm {
        /**
          * Disable submit
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Field-level errors from the app
          * @default {}
         */
        "errors"?: RecipeFormErrors | string;
        /**
          * Emitted on any field change with the full draft
         */
        "onRfChange"?: (event: RfRecipeFormCustomEvent<UserRecipeDraft>) => void;
        /**
          * Emitted on submit
         */
        "onRfSubmit"?: (event: RfRecipeFormCustomEvent<UserRecipeDraft>) => void;
        /**
          * Submit button label
          * @default 'Save recipe'
         */
        "submitLabel"?: string;
        /**
          * Form draft value
          * @default emptyDraft()
         */
        "value"?: UserRecipeDraft | string;
    }
    /**
     * Responsive grid of recipe cards. Card events bubble as custom events from this host.
     */
    interface RfRecipeGrid {
        /**
          * Favorited recipe ids
          * @default []
         */
        "favoritedIds"?: RecipeId[] | string;
        /**
          * Accessible label for the grid
          * @default 'Recipes'
         */
        "label"?: string;
        /**
          * Bubbled favorite toggle
         */
        "onRfFavoriteToggle"?: (event: RfRecipeGridCustomEvent<{
    recipe: RecipeSearchResult;
    active: boolean;
  }>) => void;
        /**
          * Bubbled recipe select
         */
        "onRfRecipeSelect"?: (event: RfRecipeGridCustomEvent<{ recipe: RecipeSearchResult }>) => void;
        /**
          * Recipes to render
          * @default []
         */
        "recipes"?: RecipeSearchResult[] | string;
    }
    /**
     * Search field with submit control.
     */
    interface RfSearchBar {
        /**
          * Disables the whole control
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Accessible label for the search field
          * @default 'Search recipes'
         */
        "label"?: string;
        /**
          * Shows loading / disables submit
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when the user submits a search
         */
        "onRfSearch"?: (event: RfSearchBarCustomEvent<{ query: string }>) => void;
        /**
          * Placeholder text
          * @default 'Search recipes…'
         */
        "placeholder"?: string;
        /**
          * Submit button label
          * @default 'Search'
         */
        "submitLabel"?: string;
        /**
          * Current query
          * @default ''
         */
        "value"?: string;
    }
    /**
     * Labeled select control.
     */
    interface RfSelect {
        /**
          * Disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Visible label
          * @default ''
         */
        "label"?: string;
        /**
          * Name attribute
         */
        "name"?: string;
        /**
          * Emitted when selection changes
         */
        "onRfChange"?: (event: RfSelectCustomEvent<string>) => void;
        /**
          * Options list (object or JSON string for attribute usage)
          * @default []
         */
        "options"?: SelectOption[] | string;
        /**
          * Placeholder option label
          * @default 'Select…'
         */
        "placeholder"?: string;
        /**
          * Required
          * @default false
         */
        "required"?: boolean;
        /**
          * Selected value
          * @default ''
         */
        "value"?: string;
    }

    interface RfButtonAttributes {
        "variant": RfButtonVariant;
        "type": RfButtonType;
        "disabled": boolean;
        "ariaLabel": string;
    }
    interface RfEmptyStateAttributes {
        "heading": string;
        "message": string;
    }
    interface RfFavoriteButtonAttributes {
        "active": boolean;
        "disabled": boolean;
        "labelInactive": string;
        "labelActive": string;
    }
    interface RfFilterPanelAttributes {
        "categories": string[] | SelectOption[] | string;
        "areas": string[] | SelectOption[] | string;
        "value": RecipeFilterValue | string;
        "showIngredient": boolean;
    }
    interface RfInputAttributes {
        "label": string;
        "value": string;
        "name": string;
        "type": string;
        "placeholder": string;
        "error": string;
        "disabled": boolean;
        "required": boolean;
        "autocomplete": string;
    }
    interface RfLoadingStateAttributes {
        "label": string;
    }
    interface RfMealPlanCardAttributes {
        "meal": PlannedMeal | string;
        "day": MealDay;
        "mealSlot": MealSlot;
    }
    interface RfMealPlanWeekAttributes {
        "weekStart": string;
        "meals": PlannedMeal[] | string;
    }
    interface RfModalAttributes {
        "open": boolean;
        "heading": string;
        "closeOnBackdrop": boolean;
    }
    interface RfRecipeCardAttributes {
        "recipe": RecipeSearchResult | string;
        "favorited": boolean;
        "hideFavorite": boolean;
    }
    interface RfRecipeFormAttributes {
        "value": UserRecipeDraft | string;
        "errors": RecipeFormErrors | string;
        "submitLabel": string;
        "disabled": boolean;
    }
    interface RfRecipeGridAttributes {
        "recipes": RecipeSearchResult[] | string;
        "favoritedIds": RecipeId[] | string;
        "label": string;
    }
    interface RfSearchBarAttributes {
        "value": string;
        "placeholder": string;
        "loading": boolean;
        "disabled": boolean;
        "label": string;
        "submitLabel": string;
    }
    interface RfSelectAttributes {
        "label": string;
        "value": string;
        "name": string;
        "options": SelectOption[] | string;
        "error": string;
        "disabled": boolean;
        "placeholder": string;
        "required": boolean;
    }

    interface IntrinsicElements {
        "rf-button": Omit<RfButton, keyof RfButtonAttributes> & { [K in keyof RfButton & keyof RfButtonAttributes]?: RfButton[K] } & { [K in keyof RfButton & keyof RfButtonAttributes as `attr:${K}`]?: RfButtonAttributes[K] } & { [K in keyof RfButton & keyof RfButtonAttributes as `prop:${K}`]?: RfButton[K] };
        "rf-empty-state": Omit<RfEmptyState, keyof RfEmptyStateAttributes> & { [K in keyof RfEmptyState & keyof RfEmptyStateAttributes]?: RfEmptyState[K] } & { [K in keyof RfEmptyState & keyof RfEmptyStateAttributes as `attr:${K}`]?: RfEmptyStateAttributes[K] } & { [K in keyof RfEmptyState & keyof RfEmptyStateAttributes as `prop:${K}`]?: RfEmptyState[K] };
        "rf-favorite-button": Omit<RfFavoriteButton, keyof RfFavoriteButtonAttributes> & { [K in keyof RfFavoriteButton & keyof RfFavoriteButtonAttributes]?: RfFavoriteButton[K] } & { [K in keyof RfFavoriteButton & keyof RfFavoriteButtonAttributes as `attr:${K}`]?: RfFavoriteButtonAttributes[K] } & { [K in keyof RfFavoriteButton & keyof RfFavoriteButtonAttributes as `prop:${K}`]?: RfFavoriteButton[K] };
        "rf-filter-panel": Omit<RfFilterPanel, keyof RfFilterPanelAttributes> & { [K in keyof RfFilterPanel & keyof RfFilterPanelAttributes]?: RfFilterPanel[K] } & { [K in keyof RfFilterPanel & keyof RfFilterPanelAttributes as `attr:${K}`]?: RfFilterPanelAttributes[K] } & { [K in keyof RfFilterPanel & keyof RfFilterPanelAttributes as `prop:${K}`]?: RfFilterPanel[K] };
        "rf-input": Omit<RfInput, keyof RfInputAttributes> & { [K in keyof RfInput & keyof RfInputAttributes]?: RfInput[K] } & { [K in keyof RfInput & keyof RfInputAttributes as `attr:${K}`]?: RfInputAttributes[K] } & { [K in keyof RfInput & keyof RfInputAttributes as `prop:${K}`]?: RfInput[K] };
        "rf-loading-state": Omit<RfLoadingState, keyof RfLoadingStateAttributes> & { [K in keyof RfLoadingState & keyof RfLoadingStateAttributes]?: RfLoadingState[K] } & { [K in keyof RfLoadingState & keyof RfLoadingStateAttributes as `attr:${K}`]?: RfLoadingStateAttributes[K] } & { [K in keyof RfLoadingState & keyof RfLoadingStateAttributes as `prop:${K}`]?: RfLoadingState[K] };
        "rf-meal-plan-card": Omit<RfMealPlanCard, keyof RfMealPlanCardAttributes> & { [K in keyof RfMealPlanCard & keyof RfMealPlanCardAttributes]?: RfMealPlanCard[K] } & { [K in keyof RfMealPlanCard & keyof RfMealPlanCardAttributes as `attr:${K}`]?: RfMealPlanCardAttributes[K] } & { [K in keyof RfMealPlanCard & keyof RfMealPlanCardAttributes as `prop:${K}`]?: RfMealPlanCard[K] } & OneOf<"day", RfMealPlanCard["day"], RfMealPlanCardAttributes["day"]> & OneOf<"mealSlot", RfMealPlanCard["mealSlot"], RfMealPlanCardAttributes["mealSlot"]>;
        "rf-meal-plan-week": Omit<RfMealPlanWeek, keyof RfMealPlanWeekAttributes> & { [K in keyof RfMealPlanWeek & keyof RfMealPlanWeekAttributes]?: RfMealPlanWeek[K] } & { [K in keyof RfMealPlanWeek & keyof RfMealPlanWeekAttributes as `attr:${K}`]?: RfMealPlanWeekAttributes[K] } & { [K in keyof RfMealPlanWeek & keyof RfMealPlanWeekAttributes as `prop:${K}`]?: RfMealPlanWeek[K] };
        "rf-modal": Omit<RfModal, keyof RfModalAttributes> & { [K in keyof RfModal & keyof RfModalAttributes]?: RfModal[K] } & { [K in keyof RfModal & keyof RfModalAttributes as `attr:${K}`]?: RfModalAttributes[K] } & { [K in keyof RfModal & keyof RfModalAttributes as `prop:${K}`]?: RfModal[K] };
        "rf-recipe-card": Omit<RfRecipeCard, keyof RfRecipeCardAttributes> & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes]?: RfRecipeCard[K] } & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes as `attr:${K}`]?: RfRecipeCardAttributes[K] } & { [K in keyof RfRecipeCard & keyof RfRecipeCardAttributes as `prop:${K}`]?: RfRecipeCard[K] } & OneOf<"recipe", RfRecipeCard["recipe"], RfRecipeCardAttributes["recipe"]>;
        "rf-recipe-form": Omit<RfRecipeForm, keyof RfRecipeFormAttributes> & { [K in keyof RfRecipeForm & keyof RfRecipeFormAttributes]?: RfRecipeForm[K] } & { [K in keyof RfRecipeForm & keyof RfRecipeFormAttributes as `attr:${K}`]?: RfRecipeFormAttributes[K] } & { [K in keyof RfRecipeForm & keyof RfRecipeFormAttributes as `prop:${K}`]?: RfRecipeForm[K] };
        "rf-recipe-grid": Omit<RfRecipeGrid, keyof RfRecipeGridAttributes> & { [K in keyof RfRecipeGrid & keyof RfRecipeGridAttributes]?: RfRecipeGrid[K] } & { [K in keyof RfRecipeGrid & keyof RfRecipeGridAttributes as `attr:${K}`]?: RfRecipeGridAttributes[K] } & { [K in keyof RfRecipeGrid & keyof RfRecipeGridAttributes as `prop:${K}`]?: RfRecipeGrid[K] };
        "rf-search-bar": Omit<RfSearchBar, keyof RfSearchBarAttributes> & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes]?: RfSearchBar[K] } & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes as `attr:${K}`]?: RfSearchBarAttributes[K] } & { [K in keyof RfSearchBar & keyof RfSearchBarAttributes as `prop:${K}`]?: RfSearchBar[K] };
        "rf-select": Omit<RfSelect, keyof RfSelectAttributes> & { [K in keyof RfSelect & keyof RfSelectAttributes]?: RfSelect[K] } & { [K in keyof RfSelect & keyof RfSelectAttributes as `attr:${K}`]?: RfSelectAttributes[K] } & { [K in keyof RfSelect & keyof RfSelectAttributes as `prop:${K}`]?: RfSelect[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Shared accessible button primitive.
             */
            "rf-button": LocalJSX.IntrinsicElements["rf-button"] & JSXBase.HTMLAttributes<HTMLRfButtonElement>;
            /**
             * Empty placeholder with optional CTA slot.
             */
            "rf-empty-state": LocalJSX.IntrinsicElements["rf-empty-state"] & JSXBase.HTMLAttributes<HTMLRfEmptyStateElement>;
            /**
             * Accessible favorite (heart) toggle button.
             */
            "rf-favorite-button": LocalJSX.IntrinsicElements["rf-favorite-button"] & JSXBase.HTMLAttributes<HTMLRfFavoriteButtonElement>;
            /**
             * Category / area / ingredient filter panel.
             */
            "rf-filter-panel": LocalJSX.IntrinsicElements["rf-filter-panel"] & JSXBase.HTMLAttributes<HTMLRfFilterPanelElement>;
            /**
             * Labeled text input with optional error and hint slot.
             */
            "rf-input": LocalJSX.IntrinsicElements["rf-input"] & JSXBase.HTMLAttributes<HTMLRfInputElement>;
            /**
             * Accessible loading indicator for content regions.
             */
            "rf-loading-state": LocalJSX.IntrinsicElements["rf-loading-state"] & JSXBase.HTMLAttributes<HTMLRfLoadingStateElement>;
            /**
             * Single planned meal cell for the week planner.
             */
            "rf-meal-plan-card": LocalJSX.IntrinsicElements["rf-meal-plan-card"] & JSXBase.HTMLAttributes<HTMLRfMealPlanCardElement>;
            /**
             * Seven-day meal planner grid.
             */
            "rf-meal-plan-week": LocalJSX.IntrinsicElements["rf-meal-plan-week"] & JSXBase.HTMLAttributes<HTMLRfMealPlanWeekElement>;
            /**
             * Accessible modal dialog with focus trap basics and Escape to close.
             */
            "rf-modal": LocalJSX.IntrinsicElements["rf-modal"] & JSXBase.HTMLAttributes<HTMLRfModalElement>;
            /**
             * Recipe summary card.
             */
            "rf-recipe-card": LocalJSX.IntrinsicElements["rf-recipe-card"] & JSXBase.HTMLAttributes<HTMLRfRecipeCardElement>;
            /**
             * Presentational create/edit recipe form. Validation messages come from the host via `errors`.
             */
            "rf-recipe-form": LocalJSX.IntrinsicElements["rf-recipe-form"] & JSXBase.HTMLAttributes<HTMLRfRecipeFormElement>;
            /**
             * Responsive grid of recipe cards. Card events bubble as custom events from this host.
             */
            "rf-recipe-grid": LocalJSX.IntrinsicElements["rf-recipe-grid"] & JSXBase.HTMLAttributes<HTMLRfRecipeGridElement>;
            /**
             * Search field with submit control.
             */
            "rf-search-bar": LocalJSX.IntrinsicElements["rf-search-bar"] & JSXBase.HTMLAttributes<HTMLRfSearchBarElement>;
            /**
             * Labeled select control.
             */
            "rf-select": LocalJSX.IntrinsicElements["rf-select"] & JSXBase.HTMLAttributes<HTMLRfSelectElement>;
        }
    }
}
